[profile.default]
# The source directory
src = 'src'
# The test directory
test = 'test'
# The artifact directory
out = 'out'
# A list of paths to look for libraries in
libs = ['lib']
# Whether to cache builds or not
cache = true
# Whether to ignore the cache
force = false
# The verbosity of tests
verbosity = 3

solc_version = '0.8.16'
optimizer = true
optimizer_runs = 1000000
via_ir = true

[rpc_endpoints]
mumbai = "${MUMBAI_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"

[etherscan]
mumbai = { key = "${ETHERSCAN_API_KEY}" }
polygon = { key = "${ETHERSCAN_API_KEY}" }
