/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export declare namespace IForwarder {
  export type ForwardRequestStruct = {
    from: string;
    to: string;
    value: BigNumberish;
    gas: BigNumberish;
    nonce: BigNumberish;
    data: BytesLike;
    validUntilTime: BigNumberish;
  };

  export type ForwardRequestStructOutput = [
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    BigNumber
  ] & {
    from: string;
    to: string;
    value: BigNumber;
    gas: BigNumber;
    nonce: BigNumber;
    data: string;
    validUntilTime: BigNumber;
  };
}

export interface ForwarderInterface extends utils.Interface {
  contractName: "Forwarder";
  functions: {
    "EIP712_DOMAIN_TYPE()": FunctionFragment;
    "GENERIC_PARAMS()": FunctionFragment;
    "_getEncoded((address,address,uint256,uint256,uint256,bytes,uint256),bytes32,bytes)": FunctionFragment;
    "domains(bytes32)": FunctionFragment;
    "execute((address,address,uint256,uint256,uint256,bytes,uint256),bytes32,bytes32,bytes,bytes)": FunctionFragment;
    "getNonce(address)": FunctionFragment;
    "registerDomainSeparator(string,string)": FunctionFragment;
    "registerRequestType(string,string)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "typeHashes(bytes32)": FunctionFragment;
    "verify((address,address,uint256,uint256,uint256,bytes,uint256),bytes32,bytes32,bytes,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "EIP712_DOMAIN_TYPE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GENERIC_PARAMS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_getEncoded",
    values: [IForwarder.ForwardRequestStruct, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "domains", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [
      IForwarder.ForwardRequestStruct,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(functionFragment: "getNonce", values: [string]): string;
  encodeFunctionData(
    functionFragment: "registerDomainSeparator",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerRequestType",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "typeHashes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [
      IForwarder.ForwardRequestStruct,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "EIP712_DOMAIN_TYPE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GENERIC_PARAMS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_getEncoded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "domains", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getNonce", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerDomainSeparator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerRequestType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "typeHashes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;

  events: {
    "DomainRegistered(bytes32,bytes)": EventFragment;
    "RequestTypeRegistered(bytes32,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DomainRegistered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RequestTypeRegistered"): EventFragment;
}

export type DomainRegisteredEvent = TypedEvent<
  [string, string],
  { domainSeparator: string; domainValue: string }
>;

export type DomainRegisteredEventFilter =
  TypedEventFilter<DomainRegisteredEvent>;

export type RequestTypeRegisteredEvent = TypedEvent<
  [string, string],
  { typeHash: string; typeStr: string }
>;

export type RequestTypeRegisteredEventFilter =
  TypedEventFilter<RequestTypeRegisteredEvent>;

export interface Forwarder extends BaseContract {
  contractName: "Forwarder";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ForwarderInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    EIP712_DOMAIN_TYPE(overrides?: CallOverrides): Promise<[string]>;

    GENERIC_PARAMS(overrides?: CallOverrides): Promise<[string]>;

    _getEncoded(
      req: IForwarder.ForwardRequestStruct,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    domains(arg0: BytesLike, overrides?: CallOverrides): Promise<[boolean]>;

    execute(
      req: IForwarder.ForwardRequestStruct,
      domainSeparator: BytesLike,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      sig: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getNonce(from: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    registerDomainSeparator(
      name: string,
      version: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    registerRequestType(
      typeName: string,
      typeSuffix: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    typeHashes(arg0: BytesLike, overrides?: CallOverrides): Promise<[boolean]>;

    verify(
      req: IForwarder.ForwardRequestStruct,
      domainSeparator: BytesLike,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      sig: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;
  };

  EIP712_DOMAIN_TYPE(overrides?: CallOverrides): Promise<string>;

  GENERIC_PARAMS(overrides?: CallOverrides): Promise<string>;

  _getEncoded(
    req: IForwarder.ForwardRequestStruct,
    requestTypeHash: BytesLike,
    suffixData: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  domains(arg0: BytesLike, overrides?: CallOverrides): Promise<boolean>;

  execute(
    req: IForwarder.ForwardRequestStruct,
    domainSeparator: BytesLike,
    requestTypeHash: BytesLike,
    suffixData: BytesLike,
    sig: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getNonce(from: string, overrides?: CallOverrides): Promise<BigNumber>;

  registerDomainSeparator(
    name: string,
    version: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  registerRequestType(
    typeName: string,
    typeSuffix: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  typeHashes(arg0: BytesLike, overrides?: CallOverrides): Promise<boolean>;

  verify(
    req: IForwarder.ForwardRequestStruct,
    domainSeparator: BytesLike,
    requestTypeHash: BytesLike,
    suffixData: BytesLike,
    sig: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  callStatic: {
    EIP712_DOMAIN_TYPE(overrides?: CallOverrides): Promise<string>;

    GENERIC_PARAMS(overrides?: CallOverrides): Promise<string>;

    _getEncoded(
      req: IForwarder.ForwardRequestStruct,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    domains(arg0: BytesLike, overrides?: CallOverrides): Promise<boolean>;

    execute(
      req: IForwarder.ForwardRequestStruct,
      domainSeparator: BytesLike,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      sig: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean, string] & { success: boolean; ret: string }>;

    getNonce(from: string, overrides?: CallOverrides): Promise<BigNumber>;

    registerDomainSeparator(
      name: string,
      version: string,
      overrides?: CallOverrides
    ): Promise<void>;

    registerRequestType(
      typeName: string,
      typeSuffix: string,
      overrides?: CallOverrides
    ): Promise<void>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    typeHashes(arg0: BytesLike, overrides?: CallOverrides): Promise<boolean>;

    verify(
      req: IForwarder.ForwardRequestStruct,
      domainSeparator: BytesLike,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      sig: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "DomainRegistered(bytes32,bytes)"(
      domainSeparator?: BytesLike | null,
      domainValue?: null
    ): DomainRegisteredEventFilter;
    DomainRegistered(
      domainSeparator?: BytesLike | null,
      domainValue?: null
    ): DomainRegisteredEventFilter;

    "RequestTypeRegistered(bytes32,string)"(
      typeHash?: BytesLike | null,
      typeStr?: null
    ): RequestTypeRegisteredEventFilter;
    RequestTypeRegistered(
      typeHash?: BytesLike | null,
      typeStr?: null
    ): RequestTypeRegisteredEventFilter;
  };

  estimateGas: {
    EIP712_DOMAIN_TYPE(overrides?: CallOverrides): Promise<BigNumber>;

    GENERIC_PARAMS(overrides?: CallOverrides): Promise<BigNumber>;

    _getEncoded(
      req: IForwarder.ForwardRequestStruct,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    domains(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    execute(
      req: IForwarder.ForwardRequestStruct,
      domainSeparator: BytesLike,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      sig: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getNonce(from: string, overrides?: CallOverrides): Promise<BigNumber>;

    registerDomainSeparator(
      name: string,
      version: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    registerRequestType(
      typeName: string,
      typeSuffix: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    typeHashes(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    verify(
      req: IForwarder.ForwardRequestStruct,
      domainSeparator: BytesLike,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      sig: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    EIP712_DOMAIN_TYPE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    GENERIC_PARAMS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _getEncoded(
      req: IForwarder.ForwardRequestStruct,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    domains(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    execute(
      req: IForwarder.ForwardRequestStruct,
      domainSeparator: BytesLike,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      sig: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getNonce(
      from: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    registerDomainSeparator(
      name: string,
      version: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    registerRequestType(
      typeName: string,
      typeSuffix: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    typeHashes(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verify(
      req: IForwarder.ForwardRequestStruct,
      domainSeparator: BytesLike,
      requestTypeHash: BytesLike,
      suffixData: BytesLike,
      sig: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
