/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ShowtimeV1MarketTestInterface extends utils.Interface {
  contractName: "ShowtimeV1MarketTest";
  functions: {
    "IS_TEST()": FunctionFragment;
    "failed()": FunctionFragment;
    "onERC1155BatchReceived(address,address,uint256[],uint256[],bytes)": FunctionFragment;
    "onERC1155Received(address,address,uint256,uint256,bytes)": FunctionFragment;
    "setUp()": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "testBuySpecificQuantities()": FunctionFragment;
    "testBuyerRequestMatchesListing()": FunctionFragment;
    "testCanBuy()": FunctionFragment;
    "testCanBuyForSomeoneElse()": FunctionFragment;
    "testCanCancelWhenPaused()": FunctionFragment;
    "testCanCompleteAFullRoyaltySaleIfNoCap()": FunctionFragment;
    "testCanCompletePartialSale()": FunctionFragment;
    "testCanCompleteSaleWithCappedRoyalties()": FunctionFragment;
    "testCanCompleteSaleWithRoyalties()": FunctionFragment;
    "testCanCompleteSaleWithZeroAddressRoyalties()": FunctionFragment;
    "testCanCreateListing()": FunctionFragment;
    "testCanDisableRoyaltiesBySettingCapTo0()": FunctionFragment;
    "testCannotBuy0Tokens()": FunctionFragment;
    "testCannotBuyCancelledSale()": FunctionFragment;
    "testCannotBuyForBurnAddress()": FunctionFragment;
    "testCannotBuyMoreThanAvailable()": FunctionFragment;
    "testCannotBuyMoreThanListed()": FunctionFragment;
    "testCannotBuyWhenPaused()": FunctionFragment;
    "testCannotCancelNonExistentSale()": FunctionFragment;
    "testCannotCancelSomeonesSale()": FunctionFragment;
    "testCannotCapRoyaltiesOver100Percent()": FunctionFragment;
    "testCannotCreateListingWhenPaused()": FunctionFragment;
    "testChecksBuyerCanPay()": FunctionFragment;
    "testCorrectConstructorArguments()": FunctionFragment;
    "testCreateFreeListing()": FunctionFragment;
    "testIncorrectConstructorArguments()": FunctionFragment;
    "testListingUsesAcceptedCurrenciesOnly()": FunctionFragment;
    "testNoRoyaltiesArePaidWhenDisabled()": FunctionFragment;
    "testOnlyOwnerCanAddCurrencies()": FunctionFragment;
    "testOnlyOwnerCanDisableRoyalties()": FunctionFragment;
    "testOnlyOwnerCanPauseAndUnpause()": FunctionFragment;
    "testOnlyOwnerCanRemoveCurrencies()": FunctionFragment;
    "testOnlyOwnerCanUpdateRoyaltyCap()": FunctionFragment;
    "testSellerCanCancelSale()": FunctionFragment;
    "testSellerOwnsListedTokens()": FunctionFragment;
    "testSellerOwnsTokens()": FunctionFragment;
    "testSellersCannotSelfBuy()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "IS_TEST", values?: undefined): string;
  encodeFunctionData(functionFragment: "failed", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "onERC1155BatchReceived",
    values: [string, string, BigNumberish[], BigNumberish[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC1155Received",
    values: [string, string, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "setUp", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "testBuySpecificQuantities",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testBuyerRequestMatchesListing",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCanBuy",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCanBuyForSomeoneElse",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCanCancelWhenPaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCanCompleteAFullRoyaltySaleIfNoCap",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCanCompletePartialSale",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCanCompleteSaleWithCappedRoyalties",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCanCompleteSaleWithRoyalties",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCanCompleteSaleWithZeroAddressRoyalties",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCanCreateListing",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCanDisableRoyaltiesBySettingCapTo0",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCannotBuy0Tokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCannotBuyCancelledSale",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCannotBuyForBurnAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCannotBuyMoreThanAvailable",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCannotBuyMoreThanListed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCannotBuyWhenPaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCannotCancelNonExistentSale",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCannotCancelSomeonesSale",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCannotCapRoyaltiesOver100Percent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCannotCreateListingWhenPaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testChecksBuyerCanPay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCorrectConstructorArguments",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testCreateFreeListing",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testIncorrectConstructorArguments",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testListingUsesAcceptedCurrenciesOnly",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testNoRoyaltiesArePaidWhenDisabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testOnlyOwnerCanAddCurrencies",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testOnlyOwnerCanDisableRoyalties",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testOnlyOwnerCanPauseAndUnpause",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testOnlyOwnerCanRemoveCurrencies",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testOnlyOwnerCanUpdateRoyaltyCap",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testSellerCanCancelSale",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testSellerOwnsListedTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testSellerOwnsTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testSellersCannotSelfBuy",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "IS_TEST", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "failed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155BatchReceived",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setUp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testBuySpecificQuantities",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testBuyerRequestMatchesListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "testCanBuy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "testCanBuyForSomeoneElse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCanCancelWhenPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCanCompleteAFullRoyaltySaleIfNoCap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCanCompletePartialSale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCanCompleteSaleWithCappedRoyalties",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCanCompleteSaleWithRoyalties",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCanCompleteSaleWithZeroAddressRoyalties",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCanCreateListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCanDisableRoyaltiesBySettingCapTo0",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCannotBuy0Tokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCannotBuyCancelledSale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCannotBuyForBurnAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCannotBuyMoreThanAvailable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCannotBuyMoreThanListed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCannotBuyWhenPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCannotCancelNonExistentSale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCannotCancelSomeonesSale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCannotCapRoyaltiesOver100Percent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCannotCreateListingWhenPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testChecksBuyerCanPay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCorrectConstructorArguments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testCreateFreeListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testIncorrectConstructorArguments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testListingUsesAcceptedCurrenciesOnly",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testNoRoyaltiesArePaidWhenDisabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testOnlyOwnerCanAddCurrencies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testOnlyOwnerCanDisableRoyalties",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testOnlyOwnerCanPauseAndUnpause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testOnlyOwnerCanRemoveCurrencies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testOnlyOwnerCanUpdateRoyaltyCap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testSellerCanCancelSale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testSellerOwnsListedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testSellerOwnsTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testSellersCannotSelfBuy",
    data: BytesLike
  ): Result;

  events: {
    "AcceptedCurrencyChanged(address,address,bool)": EventFragment;
    "ListingCreated(uint256,address,uint256)": EventFragment;
    "ListingDeleted(uint256,address)": EventFragment;
    "MaxRoyaltiesUpdated(address,uint256)": EventFragment;
    "RoyaltiesEnabledChanged(address,bool)": EventFragment;
    "RoyaltyPaid(address,address,uint256)": EventFragment;
    "SaleCompleted(uint256,address,address,address,uint256)": EventFragment;
    "log(string)": EventFragment;
    "log_address(address)": EventFragment;
    "log_bytes(bytes)": EventFragment;
    "log_bytes32(bytes32)": EventFragment;
    "log_int(int256)": EventFragment;
    "log_named_address(string,address)": EventFragment;
    "log_named_bytes(string,bytes)": EventFragment;
    "log_named_bytes32(string,bytes32)": EventFragment;
    "log_named_decimal_int(string,int256,uint256)": EventFragment;
    "log_named_decimal_uint(string,uint256,uint256)": EventFragment;
    "log_named_int(string,int256)": EventFragment;
    "log_named_string(string,string)": EventFragment;
    "log_named_uint(string,uint256)": EventFragment;
    "log_string(string)": EventFragment;
    "log_uint(uint256)": EventFragment;
    "logs(bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AcceptedCurrencyChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ListingCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ListingDeleted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MaxRoyaltiesUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoyaltiesEnabledChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoyaltyPaid"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SaleCompleted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_address"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_bytes"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_bytes32"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_int"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_address"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_bytes"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_bytes32"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_decimal_int"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_decimal_uint"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_int"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_string"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_named_uint"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_string"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "log_uint"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "logs"): EventFragment;
}

export type AcceptedCurrencyChangedEvent = TypedEvent<
  [string, string, boolean],
  { account: string; currency: string; accepted: boolean }
>;

export type AcceptedCurrencyChangedEventFilter =
  TypedEventFilter<AcceptedCurrencyChangedEvent>;

export type ListingCreatedEvent = TypedEvent<
  [BigNumber, string, BigNumber],
  { listingId: BigNumber; seller: string; tokenId: BigNumber }
>;

export type ListingCreatedEventFilter = TypedEventFilter<ListingCreatedEvent>;

export type ListingDeletedEvent = TypedEvent<
  [BigNumber, string],
  { listingId: BigNumber; seller: string }
>;

export type ListingDeletedEventFilter = TypedEventFilter<ListingDeletedEvent>;

export type MaxRoyaltiesUpdatedEvent = TypedEvent<
  [string, BigNumber],
  { account: string; maxRoyaltiesBasisPoints: BigNumber }
>;

export type MaxRoyaltiesUpdatedEventFilter =
  TypedEventFilter<MaxRoyaltiesUpdatedEvent>;

export type RoyaltiesEnabledChangedEvent = TypedEvent<
  [string, boolean],
  { account: string; royaltiesEnabled: boolean }
>;

export type RoyaltiesEnabledChangedEventFilter =
  TypedEventFilter<RoyaltiesEnabledChangedEvent>;

export type RoyaltyPaidEvent = TypedEvent<
  [string, string, BigNumber],
  { receiver: string; currency: string; amount: BigNumber }
>;

export type RoyaltyPaidEventFilter = TypedEventFilter<RoyaltyPaidEvent>;

export type SaleCompletedEvent = TypedEvent<
  [BigNumber, string, string, string, BigNumber],
  {
    listingId: BigNumber;
    seller: string;
    buyer: string;
    receiver: string;
    quantity: BigNumber;
  }
>;

export type SaleCompletedEventFilter = TypedEventFilter<SaleCompletedEvent>;

export type logEvent = TypedEvent<[string], { arg0: string }>;

export type logEventFilter = TypedEventFilter<logEvent>;

export type log_addressEvent = TypedEvent<[string], { arg0: string }>;

export type log_addressEventFilter = TypedEventFilter<log_addressEvent>;

export type log_bytesEvent = TypedEvent<[string], { arg0: string }>;

export type log_bytesEventFilter = TypedEventFilter<log_bytesEvent>;

export type log_bytes32Event = TypedEvent<[string], { arg0: string }>;

export type log_bytes32EventFilter = TypedEventFilter<log_bytes32Event>;

export type log_intEvent = TypedEvent<[BigNumber], { arg0: BigNumber }>;

export type log_intEventFilter = TypedEventFilter<log_intEvent>;

export type log_named_addressEvent = TypedEvent<
  [string, string],
  { key: string; val: string }
>;

export type log_named_addressEventFilter =
  TypedEventFilter<log_named_addressEvent>;

export type log_named_bytesEvent = TypedEvent<
  [string, string],
  { key: string; val: string }
>;

export type log_named_bytesEventFilter = TypedEventFilter<log_named_bytesEvent>;

export type log_named_bytes32Event = TypedEvent<
  [string, string],
  { key: string; val: string }
>;

export type log_named_bytes32EventFilter =
  TypedEventFilter<log_named_bytes32Event>;

export type log_named_decimal_intEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  { key: string; val: BigNumber; decimals: BigNumber }
>;

export type log_named_decimal_intEventFilter =
  TypedEventFilter<log_named_decimal_intEvent>;

export type log_named_decimal_uintEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  { key: string; val: BigNumber; decimals: BigNumber }
>;

export type log_named_decimal_uintEventFilter =
  TypedEventFilter<log_named_decimal_uintEvent>;

export type log_named_intEvent = TypedEvent<
  [string, BigNumber],
  { key: string; val: BigNumber }
>;

export type log_named_intEventFilter = TypedEventFilter<log_named_intEvent>;

export type log_named_stringEvent = TypedEvent<
  [string, string],
  { key: string; val: string }
>;

export type log_named_stringEventFilter =
  TypedEventFilter<log_named_stringEvent>;

export type log_named_uintEvent = TypedEvent<
  [string, BigNumber],
  { key: string; val: BigNumber }
>;

export type log_named_uintEventFilter = TypedEventFilter<log_named_uintEvent>;

export type log_stringEvent = TypedEvent<[string], { arg0: string }>;

export type log_stringEventFilter = TypedEventFilter<log_stringEvent>;

export type log_uintEvent = TypedEvent<[BigNumber], { arg0: BigNumber }>;

export type log_uintEventFilter = TypedEventFilter<log_uintEvent>;

export type logsEvent = TypedEvent<[string], { arg0: string }>;

export type logsEventFilter = TypedEventFilter<logsEvent>;

export interface ShowtimeV1MarketTest extends BaseContract {
  contractName: "ShowtimeV1MarketTest";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ShowtimeV1MarketTestInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    IS_TEST(overrides?: CallOverrides): Promise<[boolean]>;

    failed(overrides?: CallOverrides): Promise<[boolean]>;

    onERC1155BatchReceived(
      arg0: string,
      arg1: string,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    onERC1155Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setUp(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    testBuySpecificQuantities(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testBuyerRequestMatchesListing(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testCanBuy(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testCanBuyForSomeoneElse(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testCanCancelWhenPaused(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testCanCompleteAFullRoyaltySaleIfNoCap(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testCanCompletePartialSale(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testCanCompleteSaleWithCappedRoyalties(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testCanCompleteSaleWithRoyalties(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testCanCompleteSaleWithZeroAddressRoyalties(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testCanCreateListing(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testCanDisableRoyaltiesBySettingCapTo0(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testCannotBuy0Tokens(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testCannotBuyCancelledSale(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testCannotBuyForBurnAddress(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testCannotBuyMoreThanAvailable(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testCannotBuyMoreThanListed(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testCannotBuyWhenPaused(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testCannotCancelNonExistentSale(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testCannotCancelSomeonesSale(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testCannotCapRoyaltiesOver100Percent(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testCannotCreateListingWhenPaused(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testChecksBuyerCanPay(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testCorrectConstructorArguments(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testCreateFreeListing(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testIncorrectConstructorArguments(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testListingUsesAcceptedCurrenciesOnly(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testNoRoyaltiesArePaidWhenDisabled(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testOnlyOwnerCanAddCurrencies(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testOnlyOwnerCanDisableRoyalties(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testOnlyOwnerCanPauseAndUnpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testOnlyOwnerCanRemoveCurrencies(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testOnlyOwnerCanUpdateRoyaltyCap(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testSellerCanCancelSale(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testSellerOwnsListedTokens(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testSellerOwnsTokens(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    testSellersCannotSelfBuy(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  IS_TEST(overrides?: CallOverrides): Promise<boolean>;

  failed(overrides?: CallOverrides): Promise<boolean>;

  onERC1155BatchReceived(
    arg0: string,
    arg1: string,
    arg2: BigNumberish[],
    arg3: BigNumberish[],
    arg4: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  onERC1155Received(
    arg0: string,
    arg1: string,
    arg2: BigNumberish,
    arg3: BigNumberish,
    arg4: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setUp(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  testBuySpecificQuantities(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testBuyerRequestMatchesListing(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testCanBuy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testCanBuyForSomeoneElse(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testCanCancelWhenPaused(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testCanCompleteAFullRoyaltySaleIfNoCap(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testCanCompletePartialSale(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testCanCompleteSaleWithCappedRoyalties(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testCanCompleteSaleWithRoyalties(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testCanCompleteSaleWithZeroAddressRoyalties(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testCanCreateListing(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testCanDisableRoyaltiesBySettingCapTo0(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testCannotBuy0Tokens(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testCannotBuyCancelledSale(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testCannotBuyForBurnAddress(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testCannotBuyMoreThanAvailable(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testCannotBuyMoreThanListed(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testCannotBuyWhenPaused(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testCannotCancelNonExistentSale(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testCannotCancelSomeonesSale(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testCannotCapRoyaltiesOver100Percent(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testCannotCreateListingWhenPaused(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testChecksBuyerCanPay(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testCorrectConstructorArguments(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testCreateFreeListing(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testIncorrectConstructorArguments(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testListingUsesAcceptedCurrenciesOnly(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testNoRoyaltiesArePaidWhenDisabled(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testOnlyOwnerCanAddCurrencies(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testOnlyOwnerCanDisableRoyalties(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testOnlyOwnerCanPauseAndUnpause(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testOnlyOwnerCanRemoveCurrencies(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testOnlyOwnerCanUpdateRoyaltyCap(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testSellerCanCancelSale(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testSellerOwnsListedTokens(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testSellerOwnsTokens(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  testSellersCannotSelfBuy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    IS_TEST(overrides?: CallOverrides): Promise<boolean>;

    failed(overrides?: CallOverrides): Promise<boolean>;

    onERC1155BatchReceived(
      arg0: string,
      arg1: string,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    onERC1155Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    setUp(overrides?: CallOverrides): Promise<void>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    testBuySpecificQuantities(overrides?: CallOverrides): Promise<void>;

    testBuyerRequestMatchesListing(overrides?: CallOverrides): Promise<void>;

    testCanBuy(overrides?: CallOverrides): Promise<void>;

    testCanBuyForSomeoneElse(overrides?: CallOverrides): Promise<void>;

    testCanCancelWhenPaused(overrides?: CallOverrides): Promise<void>;

    testCanCompleteAFullRoyaltySaleIfNoCap(
      overrides?: CallOverrides
    ): Promise<void>;

    testCanCompletePartialSale(overrides?: CallOverrides): Promise<void>;

    testCanCompleteSaleWithCappedRoyalties(
      overrides?: CallOverrides
    ): Promise<void>;

    testCanCompleteSaleWithRoyalties(overrides?: CallOverrides): Promise<void>;

    testCanCompleteSaleWithZeroAddressRoyalties(
      overrides?: CallOverrides
    ): Promise<void>;

    testCanCreateListing(overrides?: CallOverrides): Promise<void>;

    testCanDisableRoyaltiesBySettingCapTo0(
      overrides?: CallOverrides
    ): Promise<void>;

    testCannotBuy0Tokens(overrides?: CallOverrides): Promise<void>;

    testCannotBuyCancelledSale(overrides?: CallOverrides): Promise<void>;

    testCannotBuyForBurnAddress(overrides?: CallOverrides): Promise<void>;

    testCannotBuyMoreThanAvailable(overrides?: CallOverrides): Promise<void>;

    testCannotBuyMoreThanListed(overrides?: CallOverrides): Promise<void>;

    testCannotBuyWhenPaused(overrides?: CallOverrides): Promise<void>;

    testCannotCancelNonExistentSale(overrides?: CallOverrides): Promise<void>;

    testCannotCancelSomeonesSale(overrides?: CallOverrides): Promise<void>;

    testCannotCapRoyaltiesOver100Percent(
      overrides?: CallOverrides
    ): Promise<void>;

    testCannotCreateListingWhenPaused(overrides?: CallOverrides): Promise<void>;

    testChecksBuyerCanPay(overrides?: CallOverrides): Promise<void>;

    testCorrectConstructorArguments(overrides?: CallOverrides): Promise<void>;

    testCreateFreeListing(overrides?: CallOverrides): Promise<void>;

    testIncorrectConstructorArguments(overrides?: CallOverrides): Promise<void>;

    testListingUsesAcceptedCurrenciesOnly(
      overrides?: CallOverrides
    ): Promise<void>;

    testNoRoyaltiesArePaidWhenDisabled(
      overrides?: CallOverrides
    ): Promise<void>;

    testOnlyOwnerCanAddCurrencies(overrides?: CallOverrides): Promise<void>;

    testOnlyOwnerCanDisableRoyalties(overrides?: CallOverrides): Promise<void>;

    testOnlyOwnerCanPauseAndUnpause(overrides?: CallOverrides): Promise<void>;

    testOnlyOwnerCanRemoveCurrencies(overrides?: CallOverrides): Promise<void>;

    testOnlyOwnerCanUpdateRoyaltyCap(overrides?: CallOverrides): Promise<void>;

    testSellerCanCancelSale(overrides?: CallOverrides): Promise<void>;

    testSellerOwnsListedTokens(overrides?: CallOverrides): Promise<void>;

    testSellerOwnsTokens(overrides?: CallOverrides): Promise<void>;

    testSellersCannotSelfBuy(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "AcceptedCurrencyChanged(address,address,bool)"(
      account?: string | null,
      currency?: null,
      accepted?: null
    ): AcceptedCurrencyChangedEventFilter;
    AcceptedCurrencyChanged(
      account?: string | null,
      currency?: null,
      accepted?: null
    ): AcceptedCurrencyChangedEventFilter;

    "ListingCreated(uint256,address,uint256)"(
      listingId?: BigNumberish | null,
      seller?: string | null,
      tokenId?: BigNumberish | null
    ): ListingCreatedEventFilter;
    ListingCreated(
      listingId?: BigNumberish | null,
      seller?: string | null,
      tokenId?: BigNumberish | null
    ): ListingCreatedEventFilter;

    "ListingDeleted(uint256,address)"(
      listingId?: BigNumberish | null,
      seller?: string | null
    ): ListingDeletedEventFilter;
    ListingDeleted(
      listingId?: BigNumberish | null,
      seller?: string | null
    ): ListingDeletedEventFilter;

    "MaxRoyaltiesUpdated(address,uint256)"(
      account?: string | null,
      maxRoyaltiesBasisPoints?: null
    ): MaxRoyaltiesUpdatedEventFilter;
    MaxRoyaltiesUpdated(
      account?: string | null,
      maxRoyaltiesBasisPoints?: null
    ): MaxRoyaltiesUpdatedEventFilter;

    "RoyaltiesEnabledChanged(address,bool)"(
      account?: string | null,
      royaltiesEnabled?: null
    ): RoyaltiesEnabledChangedEventFilter;
    RoyaltiesEnabledChanged(
      account?: string | null,
      royaltiesEnabled?: null
    ): RoyaltiesEnabledChangedEventFilter;

    "RoyaltyPaid(address,address,uint256)"(
      receiver?: string | null,
      currency?: null,
      amount?: null
    ): RoyaltyPaidEventFilter;
    RoyaltyPaid(
      receiver?: string | null,
      currency?: null,
      amount?: null
    ): RoyaltyPaidEventFilter;

    "SaleCompleted(uint256,address,address,address,uint256)"(
      listingId?: BigNumberish | null,
      seller?: string | null,
      buyer?: string | null,
      receiver?: null,
      quantity?: null
    ): SaleCompletedEventFilter;
    SaleCompleted(
      listingId?: BigNumberish | null,
      seller?: string | null,
      buyer?: string | null,
      receiver?: null,
      quantity?: null
    ): SaleCompletedEventFilter;

    "log(string)"(arg0?: null): logEventFilter;
    log(arg0?: null): logEventFilter;

    "log_address(address)"(arg0?: null): log_addressEventFilter;
    log_address(arg0?: null): log_addressEventFilter;

    "log_bytes(bytes)"(arg0?: null): log_bytesEventFilter;
    log_bytes(arg0?: null): log_bytesEventFilter;

    "log_bytes32(bytes32)"(arg0?: null): log_bytes32EventFilter;
    log_bytes32(arg0?: null): log_bytes32EventFilter;

    "log_int(int256)"(arg0?: null): log_intEventFilter;
    log_int(arg0?: null): log_intEventFilter;

    "log_named_address(string,address)"(
      key?: null,
      val?: null
    ): log_named_addressEventFilter;
    log_named_address(key?: null, val?: null): log_named_addressEventFilter;

    "log_named_bytes(string,bytes)"(
      key?: null,
      val?: null
    ): log_named_bytesEventFilter;
    log_named_bytes(key?: null, val?: null): log_named_bytesEventFilter;

    "log_named_bytes32(string,bytes32)"(
      key?: null,
      val?: null
    ): log_named_bytes32EventFilter;
    log_named_bytes32(key?: null, val?: null): log_named_bytes32EventFilter;

    "log_named_decimal_int(string,int256,uint256)"(
      key?: null,
      val?: null,
      decimals?: null
    ): log_named_decimal_intEventFilter;
    log_named_decimal_int(
      key?: null,
      val?: null,
      decimals?: null
    ): log_named_decimal_intEventFilter;

    "log_named_decimal_uint(string,uint256,uint256)"(
      key?: null,
      val?: null,
      decimals?: null
    ): log_named_decimal_uintEventFilter;
    log_named_decimal_uint(
      key?: null,
      val?: null,
      decimals?: null
    ): log_named_decimal_uintEventFilter;

    "log_named_int(string,int256)"(
      key?: null,
      val?: null
    ): log_named_intEventFilter;
    log_named_int(key?: null, val?: null): log_named_intEventFilter;

    "log_named_string(string,string)"(
      key?: null,
      val?: null
    ): log_named_stringEventFilter;
    log_named_string(key?: null, val?: null): log_named_stringEventFilter;

    "log_named_uint(string,uint256)"(
      key?: null,
      val?: null
    ): log_named_uintEventFilter;
    log_named_uint(key?: null, val?: null): log_named_uintEventFilter;

    "log_string(string)"(arg0?: null): log_stringEventFilter;
    log_string(arg0?: null): log_stringEventFilter;

    "log_uint(uint256)"(arg0?: null): log_uintEventFilter;
    log_uint(arg0?: null): log_uintEventFilter;

    "logs(bytes)"(arg0?: null): logsEventFilter;
    logs(arg0?: null): logsEventFilter;
  };

  estimateGas: {
    IS_TEST(overrides?: CallOverrides): Promise<BigNumber>;

    failed(overrides?: CallOverrides): Promise<BigNumber>;

    onERC1155BatchReceived(
      arg0: string,
      arg1: string,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    onERC1155Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setUp(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    testBuySpecificQuantities(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testBuyerRequestMatchesListing(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testCanBuy(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testCanBuyForSomeoneElse(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testCanCancelWhenPaused(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testCanCompleteAFullRoyaltySaleIfNoCap(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testCanCompletePartialSale(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testCanCompleteSaleWithCappedRoyalties(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testCanCompleteSaleWithRoyalties(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testCanCompleteSaleWithZeroAddressRoyalties(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testCanCreateListing(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testCanDisableRoyaltiesBySettingCapTo0(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testCannotBuy0Tokens(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testCannotBuyCancelledSale(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testCannotBuyForBurnAddress(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testCannotBuyMoreThanAvailable(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testCannotBuyMoreThanListed(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testCannotBuyWhenPaused(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testCannotCancelNonExistentSale(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testCannotCancelSomeonesSale(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testCannotCapRoyaltiesOver100Percent(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testCannotCreateListingWhenPaused(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testChecksBuyerCanPay(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testCorrectConstructorArguments(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testCreateFreeListing(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testIncorrectConstructorArguments(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testListingUsesAcceptedCurrenciesOnly(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testNoRoyaltiesArePaidWhenDisabled(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testOnlyOwnerCanAddCurrencies(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testOnlyOwnerCanDisableRoyalties(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testOnlyOwnerCanPauseAndUnpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testOnlyOwnerCanRemoveCurrencies(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testOnlyOwnerCanUpdateRoyaltyCap(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testSellerCanCancelSale(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testSellerOwnsListedTokens(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testSellerOwnsTokens(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    testSellersCannotSelfBuy(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    IS_TEST(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    failed(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    onERC1155BatchReceived(
      arg0: string,
      arg1: string,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    onERC1155Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setUp(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    testBuySpecificQuantities(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testBuyerRequestMatchesListing(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testCanBuy(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testCanBuyForSomeoneElse(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testCanCancelWhenPaused(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testCanCompleteAFullRoyaltySaleIfNoCap(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testCanCompletePartialSale(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testCanCompleteSaleWithCappedRoyalties(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testCanCompleteSaleWithRoyalties(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testCanCompleteSaleWithZeroAddressRoyalties(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testCanCreateListing(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testCanDisableRoyaltiesBySettingCapTo0(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testCannotBuy0Tokens(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testCannotBuyCancelledSale(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testCannotBuyForBurnAddress(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testCannotBuyMoreThanAvailable(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testCannotBuyMoreThanListed(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testCannotBuyWhenPaused(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testCannotCancelNonExistentSale(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testCannotCancelSomeonesSale(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testCannotCapRoyaltiesOver100Percent(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testCannotCreateListingWhenPaused(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testChecksBuyerCanPay(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testCorrectConstructorArguments(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testCreateFreeListing(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testIncorrectConstructorArguments(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testListingUsesAcceptedCurrenciesOnly(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testNoRoyaltiesArePaidWhenDisabled(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testOnlyOwnerCanAddCurrencies(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testOnlyOwnerCanDisableRoyalties(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testOnlyOwnerCanPauseAndUnpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testOnlyOwnerCanRemoveCurrencies(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testOnlyOwnerCanUpdateRoyaltyCap(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testSellerCanCancelSale(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testSellerOwnsListedTokens(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testSellerOwnsTokens(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    testSellersCannotSelfBuy(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
