/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface SingleEditionMintableCreatorInterface extends utils.Interface {
  contractName: "SingleEditionMintableCreator";
  functions: {
    "createEdition(string,string,string,string,bytes32,string,bytes32,uint256,uint256)": FunctionFragment;
    "getEditionAtId(uint256)": FunctionFragment;
    "implementation()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createEdition",
    values: [
      string,
      string,
      string,
      string,
      BytesLike,
      string,
      BytesLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getEditionAtId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "implementation",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "createEdition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEditionAtId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "implementation",
    data: BytesLike
  ): Result;

  events: {
    "CreatedEdition(uint256,address,uint256,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CreatedEdition"): EventFragment;
}

export type CreatedEditionEvent = TypedEvent<
  [BigNumber, string, BigNumber, string],
  {
    editionId: BigNumber;
    creator: string;
    editionSize: BigNumber;
    editionContractAddress: string;
  }
>;

export type CreatedEditionEventFilter = TypedEventFilter<CreatedEditionEvent>;

export interface SingleEditionMintableCreator extends BaseContract {
  contractName: "SingleEditionMintableCreator";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SingleEditionMintableCreatorInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createEdition(
      _name: string,
      _symbol: string,
      _description: string,
      _animationUrl: string,
      _animationHash: BytesLike,
      _imageUrl: string,
      _imageHash: BytesLike,
      _editionSize: BigNumberish,
      _royaltyBPS: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getEditionAtId(
      editionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    implementation(overrides?: CallOverrides): Promise<[string]>;
  };

  createEdition(
    _name: string,
    _symbol: string,
    _description: string,
    _animationUrl: string,
    _animationHash: BytesLike,
    _imageUrl: string,
    _imageHash: BytesLike,
    _editionSize: BigNumberish,
    _royaltyBPS: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getEditionAtId(
    editionId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  implementation(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    createEdition(
      _name: string,
      _symbol: string,
      _description: string,
      _animationUrl: string,
      _animationHash: BytesLike,
      _imageUrl: string,
      _imageHash: BytesLike,
      _editionSize: BigNumberish,
      _royaltyBPS: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEditionAtId(
      editionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    implementation(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "CreatedEdition(uint256,address,uint256,address)"(
      editionId?: BigNumberish | null,
      creator?: string | null,
      editionSize?: null,
      editionContractAddress?: null
    ): CreatedEditionEventFilter;
    CreatedEdition(
      editionId?: BigNumberish | null,
      creator?: string | null,
      editionSize?: null,
      editionContractAddress?: null
    ): CreatedEditionEventFilter;
  };

  estimateGas: {
    createEdition(
      _name: string,
      _symbol: string,
      _description: string,
      _animationUrl: string,
      _animationHash: BytesLike,
      _imageUrl: string,
      _imageHash: BytesLike,
      _editionSize: BigNumberish,
      _royaltyBPS: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getEditionAtId(
      editionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    implementation(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    createEdition(
      _name: string,
      _symbol: string,
      _description: string,
      _animationUrl: string,
      _animationHash: BytesLike,
      _imageUrl: string,
      _imageHash: BytesLike,
      _editionSize: BigNumberish,
      _royaltyBPS: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getEditionAtId(
      editionId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    implementation(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
