/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface TestForwarderTargetInterface extends utils.Interface {
  contractName: "TestForwarderTarget";
  functions: {
    "emitMessage(string)": FunctionFragment;
    "getTrustedForwarder()": FunctionFragment;
    "isTrustedForwarder(address)": FunctionFragment;
    "mustReceiveEth(uint256)": FunctionFragment;
    "publicMsgData()": FunctionFragment;
    "publicMsgSender()": FunctionFragment;
    "testRevert()": FunctionFragment;
    "versionRecipient()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "emitMessage", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getTrustedForwarder",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isTrustedForwarder",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "mustReceiveEth",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "publicMsgData",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "publicMsgSender",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testRevert",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "versionRecipient",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "emitMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTrustedForwarder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTrustedForwarder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mustReceiveEth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publicMsgData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publicMsgSender",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "testRevert", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "versionRecipient",
    data: BytesLike
  ): Result;

  events: {
    "Reverting(string)": EventFragment;
    "TestForwarderMessage(string,bytes,address,address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Reverting"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TestForwarderMessage"): EventFragment;
}

export type RevertingEvent = TypedEvent<[string], { message: string }>;

export type RevertingEventFilter = TypedEventFilter<RevertingEvent>;

export type TestForwarderMessageEvent = TypedEvent<
  [string, string, string, string, string],
  {
    message: string;
    realMsgData: string;
    realSender: string;
    msgSender: string;
    origin: string;
  }
>;

export type TestForwarderMessageEventFilter =
  TypedEventFilter<TestForwarderMessageEvent>;

export interface TestForwarderTarget extends BaseContract {
  contractName: "TestForwarderTarget";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TestForwarderTargetInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    emitMessage(
      message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getTrustedForwarder(
      overrides?: CallOverrides
    ): Promise<[string] & { forwarder: string }>;

    isTrustedForwarder(
      forwarder: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    mustReceiveEth(
      value: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    publicMsgData(overrides?: CallOverrides): Promise<[string]>;

    publicMsgSender(overrides?: CallOverrides): Promise<[string]>;

    testRevert(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    versionRecipient(overrides?: CallOverrides): Promise<[string]>;
  };

  emitMessage(
    message: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getTrustedForwarder(overrides?: CallOverrides): Promise<string>;

  isTrustedForwarder(
    forwarder: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  mustReceiveEth(
    value: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  publicMsgData(overrides?: CallOverrides): Promise<string>;

  publicMsgSender(overrides?: CallOverrides): Promise<string>;

  testRevert(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  versionRecipient(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    emitMessage(message: string, overrides?: CallOverrides): Promise<void>;

    getTrustedForwarder(overrides?: CallOverrides): Promise<string>;

    isTrustedForwarder(
      forwarder: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    mustReceiveEth(
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    publicMsgData(overrides?: CallOverrides): Promise<string>;

    publicMsgSender(overrides?: CallOverrides): Promise<string>;

    testRevert(overrides?: CallOverrides): Promise<void>;

    versionRecipient(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "Reverting(string)"(message?: null): RevertingEventFilter;
    Reverting(message?: null): RevertingEventFilter;

    "TestForwarderMessage(string,bytes,address,address,address)"(
      message?: null,
      realMsgData?: null,
      realSender?: null,
      msgSender?: null,
      origin?: null
    ): TestForwarderMessageEventFilter;
    TestForwarderMessage(
      message?: null,
      realMsgData?: null,
      realSender?: null,
      msgSender?: null,
      origin?: null
    ): TestForwarderMessageEventFilter;
  };

  estimateGas: {
    emitMessage(
      message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getTrustedForwarder(overrides?: CallOverrides): Promise<BigNumber>;

    isTrustedForwarder(
      forwarder: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    mustReceiveEth(
      value: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    publicMsgData(overrides?: CallOverrides): Promise<BigNumber>;

    publicMsgSender(overrides?: CallOverrides): Promise<BigNumber>;

    testRevert(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    versionRecipient(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    emitMessage(
      message: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getTrustedForwarder(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isTrustedForwarder(
      forwarder: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    mustReceiveEth(
      value: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    publicMsgData(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    publicMsgSender(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    testRevert(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    versionRecipient(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
